[pytest]
# addopts = --ignore-glob=**/_pytesttester.py does not suppress a silly warning from numpy.
# because (Copilot tells me) the suppression happens too late in the collection process.
# So we just ignore the warning instead.
filterwarnings =
    ignore:cannot collect 'test' because it is not a function:pytest.PytestCollectionWarning

