"""Program version and optional Git build identification."""

import subprocess
from pathlib import Path
from extraLoggers import mustsee

try:
    # This module is generated by cewe2pdf.spec while building a PyInstaller
    # executable.  It is deliberately absent from a normal source checkout.
    from frozenBuildInfo import FROZEN_GIT_BUILD_IDENTIFICATION
except ImportError:
    FROZEN_GIT_BUILD_IDENTIFICATION = None


# Change this deliberately when a change to bash0/cewe2pdf master warrants a
# new user-facing version.  The successful-master GitHub workflow adds the
# automatic build number to its tag.
PROGRAM_VERSION = "1.0"


def getGitBuildIdentification():
    """Return the nearest cewe2pdf build tag and revision, if Git is available."""
    if FROZEN_GIT_BUILD_IDENTIFICATION is not None:
        return FROZEN_GIT_BUILD_IDENTIFICATION

    try:
        result = subprocess.run(
            ["git", "describe", "--tags", "--long", "--always", "--dirty",
             "--match", "cewe2pdf-v*"],
            cwd=Path(__file__).resolve().parent,
            check=True,
            capture_output=True,
            text=True,
        )
    except (FileNotFoundError, OSError, subprocess.CalledProcessError):
        return None

    return result.stdout.strip() or None


def getVersionInformationText():
    """Return the user-facing version and available Git provenance."""
    gitBuildIdentification = getGitBuildIdentification()
    if gitBuildIdentification is None:
        return f"cewe2pdf version {PROGRAM_VERSION}; Git identification is unavailable"
    return f"cewe2pdf version {PROGRAM_VERSION}; Git identification: {gitBuildIdentification}"


def logVersionInformation():
    """Log the user-facing version and Git provenance when it is available."""
    mustsee.info(getVersionInformationText())
